# SPDX-License-Identifier: PMPL-1.0-or-later
name: CI
permissions:
  contents: read

on:
npermissions:
  contents: read

  push:
    branches: ["main"]
  pull_request:

jobs:
  core-fill-tests:
    runs-on: ubuntu-latest
npermissions:
  contents: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
npermissions:
  contents: read

      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
      - run: deno task test:core-fill

  extension-build:
    runs-on: ubuntu-latest
npermissions:
  contents: read

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
npermissions:
  contents: read

      - uses: dtolnay/rust-toolchain@4be9e76fd7c4901c61fb841f559994984270fce7 # stable
      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"
npermissions:
  contents: read

      - run: deno task build:wasm
      - run: deno task build
